import Footer from "./components/Footer";
import NavigationBar from "./components/NavigationBar";
import "./globals.css";

export const metadata = {
  title: "pankajkoree",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
